/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('round_setup').del()
  await knex('round_setup').insert([
    {
      "roundIndex": 1,
      "ntrials": 14,
      "firstplayer": "player2",
      "easy_defect": "player2",
      "chick_startstate": 12,
      "agent1_startstate": 2,
      "agent2_startstate": 5,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": -1,
      "agent1_starty": -2,
      "agent2_startx": 2,
      "agent2_starty": -2,
      "chick_to_1": 0.449999999999999,
      "chick_to_2": 0.6,
      "chick_to_both": 1.04999999999999
    },
    {
      "roundIndex": 2,
      "ntrials": 15,
      "firstplayer": "player1",
      "easy_defect": "both",
      "chick_startstate": 12,
      "agent1_startstate": 1,
      "agent2_startstate": 23,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": -2,
      "agent1_starty": -2,
      "agent2_startx": 2,
      "agent2_starty": 2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.6,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 3,
      "ntrials": 17,
      "firstplayer": "player2",
      "easy_defect": "player2",
      "chick_startstate": 13,
      "agent1_startstate": 22,
      "agent2_startstate": 1,
      "chick_startx": 1,
      "chick_starty": 0,
      "agent1_startx": 1,
      "agent1_starty": 2,
      "agent2_startx": -2,
      "agent2_starty": -2,
      "chick_to_1": 0.3,
      "chick_to_2": 0.75,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 4,
      "ntrials": 16,
      "firstplayer": "player1",
      "easy_defect": "both",
      "chick_startstate": 17,
      "agent1_startstate": 5,
      "agent2_startstate": 19,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": 2,
      "agent1_starty": -2,
      "agent2_startx": -2,
      "agent2_starty": 2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 5,
      "ntrials": 15,
      "firstplayer": "player2",
      "easy_defect": "player1",
      "chick_startstate": 18,
      "agent1_startstate": 1,
      "agent2_startstate": 17,
      "chick_startx": 2,
      "chick_starty": 1,
      "agent1_startx": -2,
      "agent1_starty": -2,
      "agent2_startx": 0,
      "agent2_starty": 1,
      "chick_to_1": 1.04999999999999,
      "chick_to_2": 0.3,
      "chick_to_both": 1.34999999999999
    },
    {
      "roundIndex": 6,
      "ntrials": 14,
      "firstplayer": "player1",
      "easy_defect": "player2",
      "chick_startstate": 18,
      "agent1_startstate": 17,
      "agent2_startstate": 1,
      "chick_startx": 2,
      "chick_starty": 1,
      "agent1_startx": 0,
      "agent1_starty": 1,
      "agent2_startx": -2,
      "agent2_starty": -2,
      "chick_to_1": 0.3,
      "chick_to_2": 1.04999999999999,
      "chick_to_both": 1.34999999999999
    },
    {
      "roundIndex": 7,
      "ntrials": 16,
      "firstplayer": "player2",
      "easy_defect": "both",
      "chick_startstate": 7,
      "agent1_startstate": 5,
      "agent2_startstate": 19,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": 2,
      "agent1_starty": -2,
      "agent2_startx": -2,
      "agent2_starty": 2,
      "chick_to_1": 0.449999999999999,
      "chick_to_2": 0.75,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 8,
      "ntrials": 16,
      "firstplayer": "player1",
      "easy_defect": "player2",
      "chick_startstate": 17,
      "agent1_startstate": 20,
      "agent2_startstate": 5,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": -1,
      "agent1_starty": 2,
      "agent2_startx": 2,
      "agent2_starty": -2,
      "chick_to_1": 0.3,
      "chick_to_2": 0.75,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 9,
      "ntrials": 17,
      "firstplayer": "player1",
      "easy_defect": "both",
      "chick_startstate": 7,
      "agent1_startstate": 19,
      "agent2_startstate": 5,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": -2,
      "agent1_starty": 2,
      "agent2_startx": 2,
      "agent2_starty": -2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 10,
      "ntrials": 13,
      "firstplayer": "player2",
      "easy_defect": "none",
      "chick_startstate": 7,
      "agent1_startstate": 4,
      "agent2_startstate": 20,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": 1,
      "agent1_starty": -2,
      "agent2_startx": -1,
      "agent2_starty": 2,
      "chick_to_1": 0.3,
      "chick_to_2": 0.6,
      "chick_to_both": 0.899999999999999
    },
    {
      "roundIndex": 11,
      "ntrials": 12,
      "firstplayer": "player1",
      "easy_defect": "none",
      "chick_startstate": 7,
      "agent1_startstate": 20,
      "agent2_startstate": 22,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": -1,
      "agent1_starty": 2,
      "agent2_startx": 1,
      "agent2_starty": 2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.6,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 12,
      "ntrials": 13,
      "firstplayer": "player2",
      "easy_defect": "none",
      "chick_startstate": 7,
      "agent1_startstate": 22,
      "agent2_startstate": 20,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": 1,
      "agent1_starty": 2,
      "agent2_startx": -1,
      "agent2_starty": 2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.6,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 13,
      "ntrials": 17,
      "firstplayer": "player1",
      "easy_defect": "none",
      "chick_startstate": 7,
      "agent1_startstate": 20,
      "agent2_startstate": 4,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": -1,
      "agent1_starty": 2,
      "agent2_startx": 1,
      "agent2_starty": -2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.3,
      "chick_to_both": 0.899999999999999
    },
    {
      "roundIndex": 14,
      "ntrials": 16,
      "firstplayer": "player2",
      "easy_defect": "player1",
      "chick_startstate": 16,
      "agent1_startstate": 5,
      "agent2_startstate": 17,
      "chick_startx": -2,
      "chick_starty": 1,
      "agent1_startx": 2,
      "agent1_starty": -2,
      "agent2_startx": 0,
      "agent2_starty": 1,
      "chick_to_1": 1.04999999999999,
      "chick_to_2": 0.3,
      "chick_to_both": 1.34999999999999
    },
    {
      "roundIndex": 15,
      "ntrials": 12,
      "firstplayer": "player2",
      "easy_defect": "both",
      "chick_startstate": 12,
      "agent1_startstate": 23,
      "agent2_startstate": 1,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": 2,
      "agent1_starty": 2,
      "agent2_startx": -2,
      "agent2_starty": -2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.6,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 16,
      "ntrials": 12,
      "firstplayer": "player2",
      "easy_defect": "player1",
      "chick_startstate": 17,
      "agent1_startstate": 5,
      "agent2_startstate": 20,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": 2,
      "agent1_starty": -2,
      "agent2_startx": -1,
      "agent2_starty": 2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.3,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 17,
      "ntrials": 14,
      "firstplayer": "player2",
      "easy_defect": "none",
      "chick_startstate": 12,
      "agent1_startstate": 22,
      "agent2_startstate": 2,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": 1,
      "agent1_starty": 2,
      "agent2_startx": -1,
      "agent2_starty": -2,
      "chick_to_1": 0.449999999999999,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 0.899999999999999
    },
    {
      "roundIndex": 18,
      "ntrials": 15,
      "firstplayer": "player1",
      "easy_defect": "none",
      "chick_startstate": 12,
      "agent1_startstate": 2,
      "agent2_startstate": 22,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": -1,
      "agent1_starty": -2,
      "agent2_startx": 1,
      "agent2_starty": 2,
      "chick_to_1": 0.449999999999999,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 0.899999999999999
    },
    {
      "roundIndex": 19,
      "ntrials": 13,
      "firstplayer": "player1",
      "easy_defect": "player1",
      "chick_startstate": 17,
      "agent1_startstate": 1,
      "agent2_startstate": 22,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": -2,
      "agent1_starty": -2,
      "agent2_startx": 1,
      "agent2_starty": 2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.3,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 20,
      "ntrials": 13,
      "firstplayer": "player1",
      "easy_defect": "player1",
      "chick_startstate": 12,
      "agent1_startstate": 5,
      "agent2_startstate": 2,
      "chick_startx": 0,
      "chick_starty": 0,
      "agent1_startx": 2,
      "agent1_starty": -2,
      "agent2_startx": -1,
      "agent2_starty": -2,
      "chick_to_1": 0.6,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 1.04999999999999
    },
    {
      "roundIndex": 21,
      "ntrials": 14,
      "firstplayer": "player1",
      "easy_defect": "player1",
      "chick_startstate": 13,
      "agent1_startstate": 1,
      "agent2_startstate": 22,
      "chick_startx": 1,
      "chick_starty": 0,
      "agent1_startx": -2,
      "agent1_starty": -2,
      "agent2_startx": 1,
      "agent2_starty": 2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.3,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 22,
      "ntrials": 15,
      "firstplayer": "player2",
      "easy_defect": "player2",
      "chick_startstate": 17,
      "agent1_startstate": 22,
      "agent2_startstate": 1,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": 1,
      "agent1_starty": 2,
      "agent2_startx": -2,
      "agent2_starty": -2,
      "chick_to_1": 0.3,
      "chick_to_2": 0.75,
      "chick_to_both": 1.05
    },
    {
      "roundIndex": 23,
      "ntrials": 17,
      "firstplayer": "player2",
      "easy_defect": "both",
      "chick_startstate": 17,
      "agent1_startstate": 19,
      "agent2_startstate": 5,
      "chick_startx": 0,
      "chick_starty": 1,
      "agent1_startx": -2,
      "agent1_starty": 2,
      "agent2_startx": 2,
      "agent2_starty": -2,
      "chick_to_1": 0.449999999999999,
      "chick_to_2": 0.75,
      "chick_to_both": 1.2
    },
    {
      "roundIndex": 24,
      "ntrials": 13,
      "firstplayer": "player2",
      "easy_defect": "none",
      "chick_startstate": 7,
      "agent1_startstate": 19,
      "agent2_startstate": 5,
      "chick_startx": 0,
      "chick_starty": -1,
      "agent1_startx": -2,
      "agent1_starty": 2,
      "agent2_startx": 2,
      "agent2_starty": -2,
      "chick_to_1": 0.75,
      "chick_to_2": 0.449999999999999,
      "chick_to_both": 1.2
    }
  ]);
};
